# Generated by Django 5.1.6 on 2026-02-12 01:28

import django.db.models.deletion
import registry.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appconfig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.PositiveIntegerField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_AUDITORIA', 'En auditoría'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('INCLUIDO_EN_LOTE', 'Incluido en lote')], default='BORRADOR', max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=500)),
                ('autor1_nombre', models.CharField(blank=True, max_length=255)),
                ('autor1_dni', models.CharField(blank=True, max_length=20)),
                ('autor2_nombre', models.CharField(blank=True, max_length=255)),
                ('autor2_dni', models.CharField(blank=True, max_length=20)),
                ('autor3_nombre', models.CharField(blank=True, max_length=255)),
                ('autor3_dni', models.CharField(blank=True, max_length=20)),
                ('asesor_nombre', models.CharField(blank=True, max_length=255)),
                ('asesor_dni', models.CharField(blank=True, max_length=20)),
                ('asesor_orcid', models.CharField(blank=True, max_length=255)),
                ('jurado1', models.CharField(blank=True, max_length=255)),
                ('jurado2', models.CharField(blank=True, max_length=255)),
                ('jurado3', models.CharField(blank=True, max_length=255)),
                ('resumen', models.TextField(blank=True)),
                ('keywords_raw', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appconfig.careerconfig')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThesisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('tesis_docx', 'Tesis DOCX'), ('tesis_pdf', 'Tesis PDF'), ('formulario', 'Formulario'), ('turnitin', 'Turnitin')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to=registry.models.thesis_file_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='registry.thesisrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('send', 'Enviar'), ('observe', 'Observar'), ('resubmit', 'Reenviar'), ('approve', 'Aprobar')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='registry.thesisrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
