# Generated by Django 5.1.6 on 2026-02-13 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0002_advisorconfig_jurymemberconfig'),
        ('registry', '0004_sustentation_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisrecord',
            name='asesor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='appconfig.advisorconfig'),
        ),
        migrations.AddField(
            model_name='thesisrecord',
            name='jurado1_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_jurado1', to='appconfig.jurymemberconfig'),
        ),
        migrations.AddField(
            model_name='thesisrecord',
            name='jurado2_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_jurado2', to='appconfig.jurymemberconfig'),
        ),
        migrations.AddField(
            model_name='thesisrecord',
            name='jurado3_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_jurado3', to='appconfig.jurymemberconfig'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('send', 'Enviado a auditoría'), ('observe', 'Observado'), ('resubmit', 'Reenviado a auditoría'), ('approve', 'Aprobado'), ('publish', 'Publicado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thesisrecord',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_AUDITORIA', 'En auditoría'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('POR_PUBLICAR', 'Por publicar'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=30),
        ),
    ]
