# Generated by Django 5.1.6 on 2026-02-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_thesisrecord_asesor_ref_thesisrecord_jurado1_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisrecord',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTO', 'Listo para auditoría'), ('EN_AUDITORIA', 'En auditoría'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('POR_PUBLICAR', 'Por publicar'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=30),
        ),
    ]
