# Generated by Django 5.1.6 on 2026-02-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_thesisrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisrecord',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTO', 'Listo'), ('EN_AUDITORIA', 'En auditoría'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('POR_PUBLICAR', 'Por publicar'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=30),
        ),
    ]
