# Generated by Django 5.1.6 on 2026-02-12 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('RUNNING', 'En proceso'), ('DONE', 'Completado'), ('FAILED', 'Fallido')], default='CREATED', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('output_path', models.CharField(blank=True, max_length=500)),
                ('report_path', models.CharField(blank=True, max_length=500)),
                ('zip_path', models.CharField(blank=True, max_length=500)),
                ('log_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saf_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_folder_name', models.CharField(blank=True, max_length=120)),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('OK', 'OK'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='saf.safbatch')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='registry.thesisrecord')),
            ],
            options={
                'ordering': ['record__nro'],
                'unique_together': {('batch', 'record')},
            },
        ),
    ]
