# Generated by Django 5.1.6 on 2026-02-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cargador', 'Cargador'), ('asesor', 'Asesor'), ('auditor', 'Auditor')], default='cargador', max_length=20),
        ),
    ]
