# Generated by Django 5.1.6 on 2026-02-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('orcid', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JuryMemberConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
    ]
